//! Persistent application configuration stored as TOML.
//!
//! Configuration is loaded from the platform-specific config directory
//! (`~/.config/reamped/config.toml` on Linux).  When the file is missing or
//! corrupt, [`load_config`] falls back to [`AppConfig::default`].

use dirs_next::config_dir;
use std::path::PathBuf;
use serde::{Serialize, Deserialize};
use crate::keybindings::KeyBindings;

/// Returns the platform-specific path to the config file.
///
/// The directory is created if it does not exist.  On Linux this resolves to
/// `$XDG_CONFIG_HOME/reamped/config.toml` (usually `~/.config/reamped/config.toml`).
fn config_path() -> PathBuf {
    let mut path = config_dir().expect("No config dir");
    path.push("reamped");
    std::fs::create_dir_all(&path).ok();
    path.push("config.toml");
    path
}

/// Top-level application configuration.
///
/// All fields are serialised to and deserialised from TOML via Serde.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AppConfig {
    /// Master volume (`0.0` – `1.0`).
    pub volume: f32,
    /// Start the UI in fullscreen mode.
    pub fullscreen: bool,
    /// Enable crossfade between tracks.
    pub crossfade_enabled: bool,
    /// Crossfade duration in seconds.
    pub crossfade_seconds: f32,
    /// Automatically trim leading silence from tracks.
    #[serde(default)]
    pub silence_trim_enabled: bool,
    /// Colour theme settings.
    pub theme: ThemeConfig,
    /// FFT window size for the spectrum analyser.
    pub fft_size: usize,
    /// Apply smoothing to the spectrum display.
    pub spectrum_smooth: bool,
    /// Use line-mode rendering for the spectrum.
    pub line_mode: bool,
    /// Use the legacy rendering style.
    pub old_style: bool,
    /// Number of bars in the spectrum visualiser.
    pub spectrum_bars_quantity: usize,
    /// Directories scanned for music files.
    pub music_dirs: Vec<std::path::PathBuf>,
    /// User-customisable keyboard bindings.
    pub keybindings: KeyBindings,
    /// EQ bass gain (0.0–2.0, default 1.0).
    #[serde(default = "default_eq_gain")]
    pub bass_val: f32,
    /// EQ mid gain (0.0–2.0, default 1.0).
    #[serde(default = "default_eq_gain")]
    pub mid_val: f32,
    /// EQ high gain (0.0–2.0, default 1.0).
    #[serde(default = "default_eq_gain")]
    pub high_val: f32,
    /// Stereo expander width (0.0–2.0, default 1.0).
    #[serde(default = "default_eq_gain")]
    pub width_val: f32,
    /// Target frames per second for the UI (when focused).
    #[serde(default = "default_fps")]
    pub target_fps: u32,
    /// Enable vsync (may cause freezes on Hyprland when switching workspaces).
    #[serde(default = "default_true")]
    pub vsync: bool,
    /// Play bit-perfect audio through direct ALSA hardware access
    /// (bypasses PulseAudio/PipeWire/dmix and software resampling).
    /// Falls back to the CPAL backend when unsupported or unavailable.
    #[serde(default)]
    pub bit_perfect_enabled: bool,
    /// ALSA device name for bit-perfect playback (e.g. `hw:0,0`).
    /// When empty, the first available `hw:` playback device is used.
    #[serde(default)]
    pub bit_perfect_device: String,
}

fn default_eq_gain() -> f32 { 1.0 }
fn default_fps() -> u32 { 60 }
fn default_true() -> bool { true }

/// Source of the colour theme palette.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ThemeSource {
    /// Extract colours automatically from the current album cover.
    AlbumCover,
    /// Extract colours automatically from the system wallpaper.
    SystemWallpaper,
    /// Use manually configured colour roles.
    Manual,
}

/// Full Material Design 3 colour palette with all semantic roles.
///
/// Each field is an `[r, g, b]` array where each component is 0–255.
/// This mirrors the ARGB colours generated by the Matugen engine
/// (Material Color Utilities).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct M3Palette {
    pub primary: [u8; 3],
    pub on_primary: [u8; 3],
    pub primary_container: [u8; 3],
    pub on_primary_container: [u8; 3],
    pub secondary: [u8; 3],
    pub on_secondary: [u8; 3],
    pub secondary_container: [u8; 3],
    pub on_secondary_container: [u8; 3],
    pub tertiary: [u8; 3],
    pub on_tertiary: [u8; 3],
    pub tertiary_container: [u8; 3],
    pub on_tertiary_container: [u8; 3],
    pub error: [u8; 3],
    pub on_error: [u8; 3],
    pub error_container: [u8; 3],
    pub on_error_container: [u8; 3],
    pub surface: [u8; 3],
    pub on_surface: [u8; 3],
    pub surface_variant: [u8; 3],
    pub on_surface_variant: [u8; 3],
    pub outline: [u8; 3],
    pub outline_variant: [u8; 3],
    pub background: [u8; 3],
    pub on_background: [u8; 3],
}

/// Default M3 palette (neutral dark tones).
impl Default for M3Palette {
    fn default() -> Self {
        Self {
            primary: [187, 134, 252],
            on_primary: [54, 22, 96],
            primary_container: [79, 44, 127],
            on_primary_container: [234, 221, 255],
            secondary: [204, 194, 220],
            on_secondary: [53, 45, 65],
            secondary_container: [76, 67, 89],
            on_secondary_container: [232, 222, 248],
            tertiary: [255, 183, 150],
            on_tertiary: [75, 38, 18],
            tertiary_container: [102, 58, 35],
            on_tertiary_container: [255, 219, 202],
            error: [255, 180, 171],
            on_error: [105, 29, 22],
            error_container: [147, 0, 8],
            on_error_container: [255, 218, 214],
            surface: [28, 27, 30],
            on_surface: [230, 225, 229],
            surface_variant: [73, 69, 78],
            on_surface_variant: [202, 196, 207],
            outline: [148, 142, 153],
            outline_variant: [73, 69, 78],
            background: [28, 27, 30],
            on_background: [230, 225, 229],
        }
    }
}

impl M3Palette {
    /// Lerp every colour role toward another palette.
    pub fn lerp(&self, target: &Self, t: f32) -> Self {
        fn lerp_u8(a: u8, b: u8, t: f32) -> u8 {
            (a as f32 + (b as f32 - a as f32) * t) as u8
        }
        fn lerp_c3(a: &[u8; 3], b: &[u8; 3], t: f32) -> [u8; 3] {
            [lerp_u8(a[0], b[0], t), lerp_u8(a[1], b[1], t), lerp_u8(a[2], b[2], t)]
        }

        Self {
            primary: lerp_c3(&self.primary, &target.primary, t),
            on_primary: lerp_c3(&self.on_primary, &target.on_primary, t),
            primary_container: lerp_c3(&self.primary_container, &target.primary_container, t),
            on_primary_container: lerp_c3(&self.on_primary_container, &target.on_primary_container, t),
            secondary: lerp_c3(&self.secondary, &target.secondary, t),
            on_secondary: lerp_c3(&self.on_secondary, &target.on_secondary, t),
            secondary_container: lerp_c3(&self.secondary_container, &target.secondary_container, t),
            on_secondary_container: lerp_c3(&self.on_secondary_container, &target.on_secondary_container, t),
            tertiary: lerp_c3(&self.tertiary, &target.tertiary, t),
            on_tertiary: lerp_c3(&self.on_tertiary, &target.on_tertiary, t),
            tertiary_container: lerp_c3(&self.tertiary_container, &target.tertiary_container, t),
            on_tertiary_container: lerp_c3(&self.on_tertiary_container, &target.on_tertiary_container, t),
            error: lerp_c3(&self.error, &target.error, t),
            on_error: lerp_c3(&self.on_error, &target.on_error, t),
            error_container: lerp_c3(&self.error_container, &target.error_container, t),
            on_error_container: lerp_c3(&self.on_error_container, &target.on_error_container, t),
            surface: lerp_c3(&self.surface, &target.surface, t),
            on_surface: lerp_c3(&self.on_surface, &target.on_surface, t),
            surface_variant: lerp_c3(&self.surface_variant, &target.surface_variant, t),
            on_surface_variant: lerp_c3(&self.on_surface_variant, &target.on_surface_variant, t),
            outline: lerp_c3(&self.outline, &target.outline, t),
            outline_variant: lerp_c3(&self.outline_variant, &target.outline_variant, t),
            background: lerp_c3(&self.background, &target.background, t),
            on_background: lerp_c3(&self.on_background, &target.on_background, t),
        }
    }
}

/// Colour theme configuration.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ThemeConfig {
    /// Source of the colour palette.
    pub source: ThemeSource,
    /// Base scale factor for the UI.
    pub base_scale: f32,
    /// Current palette values (may come from extraction or manual editing).
    pub palette: M3Palette,
}


impl Default for AppConfig {
    fn default() -> Self {
        Self {
            volume: 1.0,
            fullscreen: false,
            crossfade_enabled: false,
            crossfade_seconds: 6.0,
            silence_trim_enabled: false,
            theme: ThemeConfig {
                source: ThemeSource::AlbumCover,
                base_scale: 1.0,
                palette: M3Palette::default(),
            },
            fft_size: 13000,
            line_mode: false,
            old_style: false,
            spectrum_bars_quantity: 300,
            spectrum_smooth: false,
            music_dirs: Vec::new(),
            keybindings: KeyBindings::default(),
            bass_val: 1.0,
            mid_val: 1.0,
            high_val: 1.0,
            width_val: 1.0,
            target_fps: default_fps(),
            vsync: default_true(),
            bit_perfect_enabled: false,
            bit_perfect_device: String::new(),
        }
    }
}

/// Loads configuration from the platform config directory.
///
/// Returns [`AppConfig::default`] when the file cannot be read or parsed.
pub fn load_config() -> AppConfig {
    let path = config_path();

    if let Ok(data) = std::fs::read_to_string(&path) {
        toml::from_str(&data).unwrap_or_else(|_| AppConfig::default())
    } else {
        AppConfig::default()
    }
}

/// Persists the configuration to the platform config directory.
///
/// Silently ignores I/O errors (e.g. read-only filesystem).
pub fn save_config(cfg: &AppConfig) {
    let path = config_path();
    if let Ok(data) = toml::to_string_pretty(cfg) {
        let _ = std::fs::write(path, data);
    }
}

